spring.application.name=APPOINTMENT
server.port=8087

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionAppointPI
spring.datasource.username=postgres
spring.datasource.password=nadine

# JPA logic
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka logic
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# EMAIL CONFIG (Example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khaliloessouri10@gmail.com
spring.mail.password=ebolcifslcizadgx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS CONFIG (Twilio)
twilio.account_sid=YOUR_TWILIO_SID
twilio.auth_token=YOUR_TWILIO_TOKEN
spring.mail.password=YOUR_EMAIL_PASSWORD