spring.application.name=discussion-service
server.port=8088
spring.datasource.url=jdbc:postgresql://localhost:5432/DiscussionPI
spring.datasource.username=postgres
spring.datasource.password=nadine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
jwt.secret=7c1015921c5d90739574de77e2c5bb7661a555f493e0c2b0ca47f550b938368bd7e839ba6ff0dc617716913dfaf61c7bd87b57f3920241f008cd54fb6c7918fa
